services:
  eureka-server:
    build: backend/eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 30s
      timeout: 10s
      retries: 5
  api-gateway:
    build: backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
  employee-service:
    build: backend/employee-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_healthy
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
