server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
